(function(){'use strict';
const $=id=>document.getElementById(id),C=window.NutritionCore,config=window.LASO_NUTRITION_CONFIG,storageKey='laso-nutrition-session-v1';
let session=null,rows=[],editId=null,pendingId=null,busy=false,loadedDate=null,loadSeq=0,timer,refreshPromise=null,coachEpoch=0,photoBlob=null,photoPath=null,photoLoading=false,photoSelection=0,mealEstimate=null,estimateBusy=false;
const imageURLs=new Set();
let preferences=null,coachClients=[],clientEpoch=0,preferencesEpoch=0;
const defaultCoach='a20479c8-1339-4443-bc7a-9a2346cd3e26';
const format=n=>new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(n);
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,5000);}
function show(id){if(!$(id).open){if(typeof $(id).showModal==='function')$(id).showModal();else $(id).setAttribute('open','');}}
function close(id){if(busy)return;if(typeof $(id).close==='function')$(id).close();else $(id).removeAttribute('open');}
function uuid(){if(crypto.randomUUID)return crypto.randomUUID();return '10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16));}
function remember(value){session=value;if(!value){preferences=null;preferencesEpoch++;clientEpoch++;coachClients=[];$('coachClient').replaceChildren();$('clientJournal').replaceChildren();$('clientStatus').textContent='';$('preferencesForm').reset();if($('preferencesDialog').open)$('preferencesDialog').close();coachEpoch++;$('coachBtn').hidden=true;$('coachSettings').replaceChildren();$('coachStatus').textContent='';if($('coachDialog').open)$('coachDialog').close();}try{value?localStorage.setItem(storageKey,JSON.stringify(value)):localStorage.removeItem(storageKey);}catch{toast('This browser cannot keep you signed in after closing the page.');}}
function lock(value){busy=value;document.querySelectorAll('#estimatePhoto,#saveMeal,#saveWater,#login,#signup,#googleLogin,#savePreferences,#logout,#addMeal,#water8,#water16,#waterCustom,#snapMeal,#uploadMeal,#repeatMeal,#mealCamera,#mealUpload,#clearPhoto,#date,[data-close]').forEach(b=>b.disabled=value);}
function selectedTime(){const d=new Date(),p=$('date').value.split('-').map(Number);d.setFullYear(p[0],p[1]-1,p[2]);return C.localTime(d);}
async function request(path,opts={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),path.startsWith('/functions/')?60000:20000);try{return await fetch(config.url+path,{...opts,headers:{apikey:config.key,...opts.headers},signal:controller.signal});}catch{throw Error(navigator.onLine===false?'You are offline. Reconnect and retry; nothing has been confirmed saved.':'Connection interrupted. Please retry to confirm the save.');}finally{clearTimeout(timeout);}}
async function raw(path,opts={}){const res=await request(path,{...opts,headers:{'Content-Type':'application/json',...opts.headers}});const txt=await res.text();let data;try{data=txt?JSON.parse(txt):null;}catch{throw Error('Unexpected server response. Please retry.');}if(!res.ok){const err=Error(data?.msg||data?.message||data?.error_description||'Request failed.');err.code=data?.code;err.status=res.status;throw err;}return data;}
async function token(){if(!session?.access_token)throw Error('Please sign in again.');if(!session.expires_at||session.expires_at*1000<Date.now()+60000){if(!refreshPromise)refreshPromise=(async()=>{try{const v=await raw('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});remember({...v,expires_at:v.expires_at||Math.floor(Date.now()/1000)+v.expires_in});}catch(e){if(e.status===400||e.status===401){remember(null);rows=[];loadedDate=null;render();show('accountDialog');}throw e;}finally{refreshPromise=null;}})();await refreshPromise;}return session.access_token;}
async function api(path,opts={}){return raw(path,{...opts,headers:{...opts.headers,Authorization:'Bearer '+await token()}});}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function render(){for(const u of imageURLs)URL.revokeObjectURL(u);imageURLs.clear();const t=C.totals(rows),signed=!!session;$('mode').textContent=signed?'Account':'Sign in to start';$('accountBtn').textContent=signed?'Your account':'Sign in';$('notice').textContent=signed?'Your own journal · saved to your LasO account.':'Sign in or create your LasO account to start your private nutrition journal.';$('signedOut').hidden=signed;$('signedIn').hidden=!signed;$('accountEmail').textContent=session?.user?.email||'';$('preferencesBtn').hidden=!signed;renderGauge();
for(const k of C.fields)$('total-'+k).textContent=t[k]===null?'—':format(t[k]);$('waterTotal').textContent=format(t.water_oz);$('entryCount').textContent=rows.length?`${t.meals} meal${t.meals===1?'':'s'} · ${rows.length-t.meals} water entr${rows.length-t.meals===1?'y':'ies'}`:'No entries yet';$('coverage').textContent=t.meals?`${t.complete} of ${t.meals} meals have all four nutrition amounts. Totals include only entered values; blanks remain unknown.`:'Unknown amounts stay blank. Logged totals are not daily targets.';
if(navigator.onLine===false)$('notice').textContent='Offline — reconnect before saving to your account. Unsaved form values stay here while this page is open.';
const list=$('entries');list.replaceChildren();if(!rows.length){const empty=el('div',undefined,'empty');empty.append(el('strong','Start with your next meal.'),el('p','A description is enough. Add amounts when you know them.'));list.append(empty);}for(const r of rows){const item=el('article',undefined,'entry'),body=el('div'),actions=el('div',undefined,'entry-actions');item.dataset.id=r.id;item.append(el('div',r.entry_type==='water'?'W':r.meal_type[0].toUpperCase(),'mark'));body.append(el('div',(r.entry_type==='water'?'Water':r.meal_type)+' · '+new Date(r.logged_at).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}),'meta'),el('h3',r.entry_type==='water'?format(r.water_oz)+' fl oz of water':r.description));if(r.entry_type==='meal'){const bits=[['calories','kcal'],['protein_g','g protein'],['carbs_g','g carbs'],['fat_g','g fat']].filter(([k])=>r[k]!==null&&r[k]!==undefined).map(([k,u])=>format(r[k])+' '+u);body.append(el('div',bits.length?bits.join(' · '):'Nutrition amounts not entered','meta'));if(r.ai_estimate)body.append(el('p','Photo estimate · confirmed by you'+(r.edited_after_ai?' · edited':''),'metadata muted'));const edit=el('button','Edit','text-btn');edit.onclick=()=>openMeal(r);actions.append(edit);}const remove=el('button','Delete','text-btn');remove.onclick=()=>removeEntry(r);actions.append(remove);item.append(body,actions);list.append(item);if(r.photo_path)renderPhoto(r,body);}}
async function load(){const seq=++loadSeq,date=$('date').value;loadedDate=null;rows=[];$('loadError').hidden=true;render();try{let data;if(session){const b=C.bounds(date),p=new URLSearchParams({select:'*',user_id:'eq.'+session.user.id,order:'logged_at.asc,created_at.asc'});p.append('logged_at','gte.'+b.start);p.append('logged_at','lt.'+b.end);data=await api('/rest/v1/nutrition_diary_entries?'+p);}else data=[];if(seq!==loadSeq)return;rows=data||[];loadedDate=date;render();}catch(e){if(seq===loadSeq){$('loadError').textContent='Could not load this day. '+e.message;$('loadError').hidden=false;}}}
async function save(input,editing){if(!session)throw Error('Sign in to save your journal.');const row=C.validate(input);if(session){const payload={...row,user_id:session.user.id};if(input.entry_type==='meal'&&Object.hasOwn(input,'ai_estimate')){payload.source=input.ai_estimate?'photo_ai_confirmed':'self_reported';payload.ai_estimate=input.ai_estimate;payload.ai_confidence=input.ai_estimate?.confidence||null;payload.items=input.ai_estimate?.items||null;payload.edited_after_ai=!!input.edited_after_ai;}if(editing){delete payload.id;const updated=await api('/rest/v1/nutrition_diary_entries?id=eq.'+encodeURIComponent(editing),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});if(updated?.length!==1)throw Error('This entry could not be updated. Refresh and try again.');}else{try{const inserted=await api('/rest/v1/nutrition_diary_entries',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});if(inserted?.length!==1)throw Error('The save was not confirmed. Please retry.');}catch(e){if(e.code!=='23505')throw e;const found=await api('/rest/v1/nutrition_diary_entries?id=eq.'+row.id+'&select=id');if(found?.length!==1)throw e;}}}$('date').value=C.localDate(new Date(row.logged_at));await load();return row;}
function openMeal(row){if(busy)return;if(!session){show('accountDialog');return false;}$('mealForm').reset();photoSelection++;photoBlob=null;photoPath=row?.photo_path||null;photoLoading=false;mealEstimate=row?.ai_estimate||null;estimateBusy=false;$('estimateResult').replaceChildren();$('photoArea').hidden=true;$('clearPhoto').hidden=false;editId=row?.id||null;pendingId=row?.id||uuid();$('mealTitle').textContent=row?'Edit meal':'Log a meal';$('mealType').value=row?.meal_type||'breakfast';$('mealTime').value=row?C.localTime(new Date(row.logged_at)):selectedTime();$('description').value=row?.description||'';for(const k of C.fields)$(k).value=row?.[k]??'';$('macroDetails').open=!!row&&C.fields.some(k=>row[k]!==null&&row[k]!==undefined);$('mealError').textContent='';show('mealDialog');if(row?.photo_path){const epoch=photoSelection;getPhoto(row).then(blob=>{if(epoch===photoSelection){previewPhoto(blob);$('photoStatus').textContent='Saved photo. You can estimate nutrition or edit the amounts below.';$('clearPhoto').hidden=true;}}).catch(()=>{$('mealError').textContent='Saved photo could not be loaded. You can still edit the meal.';});}}
function openWater(amount){if(busy)return;if(!session){show('accountDialog');return;}$('waterForm').reset();$('waterAmount').value=amount||'';$('waterTime').value=selectedTime();$('waterForm').dataset.id=uuid();$('waterError').textContent='';show('waterDialog');}
async function removeEntry(row){if(busy||!confirm('Delete this '+(row.entry_type==='meal'?'meal':'water entry')+'?'))return;lock(true);try{if(session){if(row.photo_path)await api('/storage/v1/object/nutrition-diary-photos',{method:'DELETE',body:JSON.stringify({prefixes:[row.photo_path]})});const removed=await api('/rest/v1/nutrition_diary_entries?id=eq.'+row.id,{method:'DELETE',headers:{Prefer:'return=representation'}});if(removed?.length!==1)throw Error('The deletion was not confirmed. Refresh this day and check the entry.');}await load();toast('Entry deleted.');}catch(e){toast(e.message);}finally{lock(false);}}

let previewURL=null;
function previewPhoto(blob){if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(blob);$('photoPreview').src=previewURL;$('photoArea').hidden=false;}
async function getPhoto(row){if(!session)throw Error('Sign in to view photos.');const r=await request('/storage/v1/object/authenticated/nutrition-diary-photos/'+row.photo_path,{headers:{Authorization:'Bearer '+await token()}});if(!r.ok)throw Error('Photo unavailable');return r.blob();}
async function renderPhoto(row,parent){try{const blob=await getPhoto(row);if(!blob||!parent.isConnected)return;const img=el('img');img.alt='Food or drink photo for this entry';img.className='entry-photo';const url=URL.createObjectURL(blob);imageURLs.add(url);img.src=url;parent.append(img);}catch{if(parent.isConnected)parent.append(el('p','Photo unavailable. Refresh to retry.','metadata muted'));}}
async function selectPhoto(file){if(!file)return;const epoch=++photoSelection;photoLoading=true;$('saveMeal').disabled=true;$('mealError').textContent='Preparing photo…';try{if(file.size>25*1024*1024)throw Error('Choose an image under 25 MB.');const source=URL.createObjectURL(file);let img;try{img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('This browser cannot read that image. Take a new photo or choose a JPEG or PNG.'));image.src=source;});}finally{URL.revokeObjectURL(source);}if(epoch!==photoSelection)return;const scale=Math.min(1,1200/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',0.82));if(!blob||blob.size>2*1024*1024)throw Error('This photo is too large. Choose a smaller image.');if(epoch!==photoSelection)return;photoBlob=blob;mealEstimate=null;$('estimateResult').replaceChildren();previewPhoto(blob);$('clearPhoto').hidden=false;$('photoStatus').textContent='Photo ready. Estimate nutrition, review the result, then save your meal.';$('mealError').textContent='';}catch(e){if(epoch===photoSelection)$('mealError').textContent=e.message;}finally{if(epoch===photoSelection){photoLoading=false;$('saveMeal').disabled=busy;}}}
async function estimatePhoto(){
 if(busy||photoLoading||estimateBusy||!session)return;
 if(!photoBlob&&!photoPath){$('mealError').textContent='Choose a food photo first.';return;}
 estimateBusy=true;lock(true);$('mealError').textContent='Estimating food and portions…';
 const epoch=photoSelection,owner=session.user.id;
 try{
  const body={kind:'photo',hint:$('description').value,meal_type:$('mealType').value};
  const imageToAnalyze=photoBlob||await getPhoto({photo_path:photoPath});
  body.image_base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('Could not read this photo.'));r.readAsDataURL(imageToAnalyze);});
  const controller=new AbortController(),deadline=setTimeout(()=>controller.abort(),55000);
  let result;try{const response=await fetch('/api/nutrition-estimate',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await token()},body:JSON.stringify(body),signal:controller.signal});result=await response.json();}finally{clearTimeout(deadline);}
  if(epoch!==photoSelection||owner!==session?.user.id)return;
  if(!result?.ok)throw Object.assign(Error(window.NutritionPhoto.message(result?.code)),{code:result?.code});
  mealEstimate=window.NutritionPhoto.normalize(result.estimate);
  $('description').value=mealEstimate.meal_title+' — '+mealEstimate.items.map(i=>i.name+' ('+i.portion+')').join(', ');
  for(const k of C.fields)$(k).value=mealEstimate.totals[k];
  $('macroDetails').open=true;
  const view=$('estimateResult');view.replaceChildren(el('strong','Review your photo estimate'),el('p','Portion confidence: '+mealEstimate.confidence+'. '+mealEstimate.notes));
  const ul=el('ul');for(const item of mealEstimate.items)ul.append(el('li',item.name+' · '+item.portion+' · '+format(item.calories)+' kcal'));view.append(ul,el('p','Check portions and edit the amounts below. Nothing enters your journal until you select Save meal.'));
  $('mealError').textContent='';
 }catch(e){$('mealError').textContent=e.code?window.NutritionPhoto.message(e.code):e.message;}
 finally{estimateBusy=false;lock(false);}
}
$('estimatePhoto').onclick=estimatePhoto;
$('cameraInput').onchange=e=>selectPhoto(e.target.files[0]);$('photoInput').onchange=e=>selectPhoto(e.target.files[0]);
$('snapMeal').onclick=()=>{if(openMeal()!==false&&session)$('cameraInput').click();};$('uploadMeal').onclick=()=>{if(openMeal()!==false&&session)$('photoInput').click();};$('mealCamera').onclick=()=>$('cameraInput').click();$('mealUpload').onclick=()=>$('photoInput').click();
$('clearPhoto').onclick=()=>{photoSelection++;photoBlob=null;mealEstimate=null;$('estimateResult').replaceChildren();photoLoading=false;$('saveMeal').disabled=busy;$('photoArea').hidden=true;$('cameraInput').value='';$('photoInput').value='';$('mealError').textContent='';};
$('repeatMeal').onclick=async()=>{if(!session){show('accountDialog');return;}show('repeatDialog');const target=$('recentMeals');target.textContent='Loading recent meals…';const owner=session?.user.id;try{const meals=await api('/rest/v1/nutrition_diary_entries?user_id=eq.'+session.user.id+'&entry_type=eq.meal&order=logged_at.desc&limit=12');if(owner!==session?.user.id)return;target.replaceChildren();if(!meals.length)target.textContent='Save a meal first, then repeat it here.';for(const meal of meals){const b=el('button',meal.description);b.onclick=()=>{close('repeatDialog');openMeal({...meal,id:null,photo_path:null,logged_at:selectedTime()});editId=null;};target.append(b);}}catch(e){target.textContent=e.message;}};
async function loadCoach(){const epoch=++coachEpoch;$('coachBtn').hidden=true;$('coachSettings').replaceChildren();$('coachStatus').textContent='';if(!session)return;try{const records=await api('/rest/v1/coach_program_settings?select=accountability_phone_e164,sms_delivery_status,session_duration_minutes,session_price_cents,pack_sessions,pack_price_cents,target_sessions_per_client_per_month,additional_client_capacity,complimentary_trial_places,currency&coach_id=eq.'+encodeURIComponent(session.user.id));if(epoch!==coachEpoch||!records?.length)return;await loadClients();const s=records[0],money=v=>new Intl.NumberFormat(undefined,{style:'currency',currency:s.currency,maximumFractionDigits:0}).format(v/100);$('coachBtn').hidden=false;const values=[['Default accountability partner','You'],['Pilot text recipient',s.accountability_phone_e164],['Private session',s.session_duration_minutes+' minutes · '+money(s.session_price_cents)],['Training pack',s.pack_sessions+' sessions · '+money(s.pack_price_cents)],['Monthly target',s.target_sessions_per_client_per_month+' sessions per client'],['New paid-client capacity',String(s.additional_client_capacity)],['Complimentary trial places',String(s.complimentary_trial_places)]];for(const [label,value]of values){const div=el('div');div.append(el('dt',label),el('dd',value));$('coachSettings').append(div);}$('coachStatus').textContent=s.sms_delivery_status==='active'?'Text delivery is enabled. Client alert preferences still apply.':'Text delivery is not active. A connected SMS service and client alert preferences are needed.';}catch(e){if(epoch===coachEpoch){$('coachBtn').hidden=false;$('coachStatus').textContent='Could not load coach settings. '+e.message;}}}
$('coachBtn').onclick=()=>{show('coachDialog');loadCoach();};$('refreshCoach').onclick=loadCoach;
window.addEventListener('offline',()=>{document.body.classList.add('offline');render();});window.addEventListener('online',()=>{document.body.classList.remove('offline');render();toast('Connection restored. Retry any unconfirmed save.');});
$('date').value=C.localDate();$('date').onchange=()=>{if($('date').value)load();};$('addMeal').onclick=()=>openMeal();$('water8').onclick=()=>openWater(8);$('water16').onclick=()=>openWater(16);$('waterCustom').onclick=()=>openWater();$('accountBtn').onclick=()=>show('accountDialog');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
$('mealForm').onsubmit=async e=>{e.preventDefault();if(busy||photoLoading||estimateBusy)return;if(!session){show('accountDialog');return;}lock(true);$('mealError').textContent='';try{const row={id:pendingId,entry_type:'meal',meal_type:$('mealType').value,description:$('description').value,logged_at:$('mealTime').value};for(const k of C.fields)row[k]=$(k).value;if(photoBlob||photoPath){row.description=row.description.trim()||'Photo entry — food and portions not described';}C.validate(row);if(photoBlob){if(session){photoPath=session.user.id+'/'+pendingId+'/photo.jpg';const res=await request('/storage/v1/object/nutrition-diary-photos/'+photoPath,{method:'POST',headers:{Authorization:'Bearer '+await token(),'Content-Type':'image/jpeg','x-upsert':'true'},body:photoBlob});if(!res.ok)throw Error('Photo upload was not confirmed. Retry or remove the new photo.');}}row.photo_path=session?photoPath:null;row.ai_estimate=mealEstimate;row.edited_after_ai=!!mealEstimate&&C.fields.some(k=>Number(row[k])!==mealEstimate.totals?.[k]);await save(row,editId);$('mealDialog').close();toast('Meal saved to your account.');}catch(err){$('mealError').textContent=err.message;}finally{lock(false);}};
$('waterForm').onsubmit=async e=>{e.preventDefault();if(busy)return;if(!session){show('accountDialog');return;}lock(true);$('waterError').textContent='';try{await save({id:$('waterForm').dataset.id,entry_type:'water',water_oz:$('waterAmount').value,logged_at:$('waterTime').value});$('waterDialog').close();toast('Water saved to your account.');}catch(err){$('waterError').textContent=err.message;}finally{lock(false);}};
$('loginForm').onsubmit=async e=>{e.preventDefault();if(busy)return;lock(true);$('authError').textContent='';try{const v=await raw('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});if(!v.access_token||!v.user?.id)throw Error('Sign-in did not complete.');remember({...v,expires_at:v.expires_at||Math.floor(Date.now()/1000)+v.expires_in});$('password').value='';await load();await loadPreferences();await loadCoach();$('accountDialog').close();toast('Signed in. Your journal is ready.');}catch(err){$('authError').textContent=err.message;}finally{lock(false);}};
$('logout').onclick=async()=>{if(busy)return;lock(true);let revoked=true;try{await api('/auth/v1/logout?scope=local',{method:'POST'});}catch{revoked=false;}finally{remember(null);loadSeq++;await load();$('accountDialog').close();lock(false);toast(revoked?'Signed out on this device.':'Signed out here. Server session revocation could not be confirmed.');}};
$('export').onclick=()=>{if(!session){show('accountDialog');return;}if(loadedDate!==$('date').value){toast('Load this day successfully before exporting.');return;}const clean=rows.map(({user_id,photo_path,...r})=>({...r,has_photo:!!photo_path})),blob=new Blob([JSON.stringify({app:'App-E-Tight',date:loadedDate,mode:session?'account':'signed_out',entries:clean},null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='App-E-Tight_'+loadedDate+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};
if(document.modelContext?.registerTool){const life=new AbortController();window.addEventListener('pagehide',()=>life.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'read_current_nutrition_day',title:'Read current nutrition day',description:'Read the loaded journal date, logged totals and completeness. Does not change or save entries.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(input&&Object.keys(input).length)throw Error('No parameters are accepted.');if(loadedDate!==$('date').value)throw Error('This day is not loaded.');return {date:loadedDate,mode:session?'account':'signed_out',totals:C.totals(rows),source:'self_reported'};}},{signal:life.signal})).catch(()=>{});}catch{}}
function renderGauge(){const container=$('gauges');container.replaceChildren();const totals=C.totals(rows);let goalCount=0;for(const [label,key,goalKey,unit] of [['Energy','calories','calorie_goal','kcal'],['Protein','protein_g','protein_goal_g','g'],['Water','water_oz','water_goal_oz','fl oz']]){const goal=preferences?.[goalKey],value=totals[key],card=el('div',undefined,'gauge');const ring=el('div',undefined,'gauge-ring');const pct=goal&&value!==null?Math.round(value/goal*100):null;ring.style.setProperty('--progress',(pct===null?0:Math.min(pct,100))*3.6+'deg');ring.append(el('strong',pct===null?'—':pct+'%'));card.append(ring,el('strong',label),el('span',goal?(value===null?'Unknown':format(value))+' / '+format(goal)+' '+unit:'Goal not set','metadata muted'));container.append(card);if(goal)goalCount++;}$('gaugeNote').textContent=goalCount?'Progress toward your own goals, based on logged amounts only. Unlogged food and unknown portions are not included. This is not a recovery or readiness score.':'Add your own goals in Goals & sharing to see logged progress. No goals are assumed.';}
async function loadPreferences(){const epoch=++preferencesEpoch;preferences=null;if(!session){renderGauge();return;}try{const data=await api('/rest/v1/nutrition_preferences?user_id=eq.'+session.user.id+'&select=*');if(epoch!==preferencesEpoch)return;preferences=data?.[0]||null;renderGauge();}catch(e){if(epoch===preferencesEpoch)toast('Could not load goals and sharing. '+e.message);}}
$('preferencesBtn').onclick=async()=>{if(!session){show('accountDialog');return;}await loadPreferences();$('displayName').value=preferences?.display_name||'';$('calorieGoal').value=preferences?.calorie_goal??'';$('proteinGoal').value=preferences?.protein_goal_g??'';$('waterGoal').value=preferences?.water_goal_oz??'';$('shareCoach').checked=preferences?.share_with_coach||false;$('preferencesError').textContent='';show('preferencesDialog');};
$('preferencesForm').onsubmit=async e=>{e.preventDefault();if(busy||!session)return;lock(true);$('preferencesError').textContent='';try{const value=id=>$(id).value.trim()===''?null:Number($(id).value);const payload={user_id:session.user.id,display_name:$('displayName').value.trim(),calorie_goal:value('calorieGoal'),protein_goal_g:value('proteinGoal'),water_goal_oz:value('waterGoal'),coach_id:defaultCoach,share_with_coach:$('shareCoach').checked,updated_at:new Date().toISOString()};if(!payload.display_name)throw Error('Enter your name.');const result=await api('/rest/v1/nutrition_preferences?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});if(result?.length!==1)throw Error('Preferences were not confirmed saved. Please retry.');preferences=result[0];renderGauge();$('preferencesDialog').close();toast(payload.share_with_coach?'Saved. Reginald can now review your journal.':'Saved. Your journal is private to you.');}catch(e){$('preferencesError').textContent=e.message;}finally{lock(false);}};
$('signup').onclick=async()=>{if(busy||!$('loginForm').reportValidity())return;$('authError').textContent='';if($('password').value.length<8){$('authError').textContent='Use at least 8 characters for a new password.';return;}lock(true);try{const data=await raw('/auth/v1/signup?redirect_to='+encodeURIComponent(authFlow.callback()),{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});$('password').value='';if(data?.access_token&&data?.user?.id){remember({...data,expires_at:data.expires_at||Math.floor(Date.now()/1000)+data.expires_in});await load();await loadPreferences();await loadCoach();$('accountDialog').close();toast('Account created. Your private journal is ready.');}else{$('authError').textContent='Check your email to confirm your account, then return here and sign in. If you already have a LasO account, use its password.';}}catch(e){$('authError').textContent=e.message;}finally{lock(false);}};
async function loadClients(){const epoch=++clientEpoch,owner=session?.user.id;if(!owner)return;const prev=$('coachClient').value;try{const clients=await api('/rest/v1/nutrition_preferences?select=user_id,display_name,calorie_goal,protein_goal_g,water_goal_oz&share_with_coach=eq.true&coach_id=eq.'+owner+'&order=display_name.asc');if(epoch!==clientEpoch||owner!==session?.user.id)return;coachClients=clients||[];const select=$('coachClient');select.replaceChildren();select.append(new Option(coachClients.length?'Choose a client':'No clients sharing yet',''));for(const c of coachClients)select.append(new Option(c.display_name,c.user_id));if(coachClients.some(c=>c.user_id===prev))select.value=prev;$('clientStatus').textContent=coachClients.length?'Select a client to review their saved journal.':'Clients appear after they create an account and enable sharing in Goals & sharing.';if(select.value)await loadClientJournal();else $('clientJournal').replaceChildren();}catch(e){if(epoch===clientEpoch)$('clientStatus').textContent='Could not load clients. '+e.message;}}
async function loadClientJournal(){const epoch=++clientEpoch,id=$('coachClient').value,date=$('coachDate').value,target=$('clientJournal');target.replaceChildren();if(!id||!date)return;$('clientStatus').textContent='Loading client journal…';try{const b=C.bounds(date),p=new URLSearchParams({select:'*',user_id:'eq.'+id,order:'logged_at.asc'});p.append('logged_at','gte.'+b.start);p.append('logged_at','lt.'+b.end);const entries=await api('/rest/v1/nutrition_diary_entries?'+p);if(epoch!==clientEpoch)return;const t=C.totals(entries||[]);$('clientStatus').textContent=entries?.length?`${t.meals} meal(s) · ${format(t.water_oz)} fl oz water. ${t.complete} meal(s) include all nutrition amounts.`:'No shared entries for this day. This does not mean a meal was missed.';const client=coachClients.find(c=>c.user_id===id);if(client){const goals=[['calorie_goal','kcal'],['protein_goal_g','g protein'],['water_goal_oz','fl oz water']].filter(([k])=>client[k]!=null).map(([k,u])=>format(client[k])+' '+u);target.append(el('p',goals.length?'Client-set goals: '+goals.join(' · '):'Client has not set daily goals.','metadata muted'));}for(const row of entries||[]){const article=el('article',undefined,'coach-entry');article.append(el('p',new Date(row.logged_at).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})+' · '+(row.meal_type||'Water'),'metadata muted'),el('strong',row.entry_type==='water'?format(row.water_oz)+' fl oz water':row.description));if(row.entry_type==='meal'){const values=[['calories','kcal'],['protein_g','g protein'],['carbs_g','g carbs'],['fat_g','g fat']].filter(([k])=>row[k]!=null).map(([k,u])=>format(row[k])+' '+u);article.append(el('p',values.length?values.join(' · '):'Nutrition amounts unknown','metadata'));}target.append(article);if(row.photo_path)renderPhoto(row,article);}}catch(e){if(epoch===clientEpoch)$('clientStatus').textContent='Could not load this journal. '+e.message;}}
$('coachDate').value=C.localDate();$('coachDate').onchange=loadClientJournal;$('coachClient').onchange=loadClientJournal;

const authFlow=window.AppETightAuth.create({config,store:sessionStorage,crypto:window.crypto,location:window.location,history:window.history,raw});
$('googleStatus').hidden=!!config.googleReady;
$('googleLogin').onclick=async()=>{if(busy)return;lock(true);$('authError').textContent='';try{const url=await authFlow.beginGoogle();window.location.assign(url);}catch(e){$('authError').textContent=e.message;lock(false);}};
(async()=>{let callbackError='';try{const incoming=await authFlow.consumeCallback();if(incoming){remember({...incoming,expires_at:incoming.expires_at||Math.floor(Date.now()/1000)+incoming.expires_in});toast('Signed in. Welcome to App-E-Tight.');}}catch(e){callbackError=e.message;}
try{const stored=localStorage.getItem(storageKey);if(stored){session=JSON.parse(stored);const user=await api('/auth/v1/user');if(!user?.id)throw Error('Please sign in again.');session.user=user;remember(session);}}catch{remember(null);toast('Sign in again to reconnect your saved journal.');}await load();await loadPreferences();await loadCoach();if(callbackError){$('authError').textContent=callbackError;show('accountDialog');}})();
})();
