(function(root){'use strict';
const fields=['calories','protein_g','carbs_g','fat_g'];
function localDate(d=new Date()){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
function localTime(d=new Date()){return localDate(d)+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');}
function bounds(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error('Choose a valid date.');const start=new Date(date+'T00:00:00'),end=new Date(start);if(Number.isNaN(start.getTime()))throw Error('Choose a valid date.');end.setDate(end.getDate()+1);return {start:start.toISOString(),end:end.toISOString()};}
function amount(value,max,positive=false){if(value===null||value===undefined||value==='')return null;const n=Number(value);if(!Number.isFinite(n)||n<0||n>max||(positive&&n===0))throw Error('Check the amounts you entered.');return n;}
function validate(row){if(!row.id||!Number.isFinite(new Date(row.logged_at).getTime()))throw Error('Choose a valid entry time.');const r={id:row.id,logged_at:new Date(row.logged_at).toISOString(),entry_type:row.entry_type,source:'self_reported',meal_type:null,description:null,calories:null,protein_g:null,carbs_g:null,fat_g:null,water_oz:null,photo_path:row.photo_path||null};if(r.entry_type==='meal'){if(!['breakfast','lunch','dinner','snack'].includes(row.meal_type))throw Error('Choose a meal type.');r.meal_type=row.meal_type;r.description=String(row.description||'').trim();if(!r.description||r.description.length>3000)throw Error('Add a meal description of 1–3,000 characters.');for(const k of fields)r[k]=amount(row[k],k==='calories'?10000:1000);}else if(r.entry_type==='water'){r.water_oz=amount(row.water_oz,256,true);if(r.water_oz===null)throw Error('Enter a water amount.');}else throw Error('Choose a meal or water entry.');return r;}
function totals(rows){const meals=rows.filter(r=>r.entry_type==='meal'),result={meals:meals.length,complete:0,water_oz:0};for(const key of fields){const known=meals.filter(r=>r[key]!==null&&r[key]!==undefined);result[key]=known.length?known.reduce((sum,r)=>sum+Number(r[key]),0):null;}result.complete=meals.filter(r=>fields.every(k=>r[k]!==null&&r[k]!==undefined)).length;result.water_oz=rows.filter(r=>r.entry_type==='water').reduce((sum,r)=>sum+Number(r.water_oz||0),0);return result;}
const api={fields,localDate,localTime,bounds,validate,totals};root.NutritionCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
