(function(){'use strict';
window.NutritionHealth={create({api,getSession,onGoal,signIn}){
const $=id=>document.getElementById(id),C=window.BodyCore;
let owner=null,profile=null,fasts=[],pending=false,epoch=0;
$('healthPanel').innerHTML=`<section class="panel health-card"><p class="eyebrow">YOUR STARTING POINT</p><h2>My body & calories</h2><p class="metadata muted">Your stats. Your starting point. Refine it with your trainer as your routine changes.</p><button id="bodyEdit" class="primary">Enter my stats</button><div id="bodyNumbers" class="body-numbers"></div><p id="bodyNote" class="metadata muted">No measurements or calorie goals are assumed.</p><button id="useEnergy" hidden>Use estimate as my calorie goal</button><p id="healthStatus" role="status" class="metadata"></p></section>
<section class="panel health-card"><p class="eyebrow">YOUR EATING RHYTHM</p><h2>Fasting, on your terms.</h2><p class="metadata muted">Optional tracking. Fasting is not required for progress. Your timer records time, not your metabolic state.</p><strong id="fastClock" class="fast-clock">Not fasting</strong><p id="fastProgress" class="metadata"></p><div id="fastSetup"><label>Last food or caloric drink<input id="fastStartTime" type="datetime-local"></label><label>Personal time goal<select id="fastTarget"><option value="0">Timer only</option><option value="12">12 hours</option><option value="14">14 hours</option><option value="16">16 hours</option></select></label><label class="check"><input id="fastEligible" type="checkbox">I am 18+, not pregnant or breastfeeding, underweight, or managing an eating disorder. If I have diabetes, take glucose-lowering medication, or have a condition affected by fasting, I have checked with my clinician.</label></div><div class="flex"><button id="fastStart" class="primary">Start tracking</button><button id="fastEnd" hidden>End fast now</button><button id="fastRefresh">Refresh</button></div><p class="metadata muted">Do not change medication for a fast. Stop if you feel shaky, dizzy or unwell; seek medical help for severe symptoms.</p><details><summary>Understand the phases</summary><p><strong>After a meal:</strong> Digestion and absorption supply energy. The duration depends on the meal.</p><p><strong>Between meals and overnight:</strong> The liver helps maintain blood glucose while your body uses a mix of carbohydrate and fat.</p><p><strong>As the gap continues:</strong> Reliance on stored fat and ketones can increase. Timing varies with food, activity and the individual. The timer cannot confirm ketosis or autophagy.</p><p><strong>Eating again:</strong> Food supplies energy, protein and other nutrients. A longer fast is not automatically better.</p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5783752/" target="_blank" rel="noopener">Fasting physiology research</a> · <a href="https://www.niddk.nih.gov/health-information/professionals/diabetes-discoveries-practice/fasting-safely-with-diabetes" target="_blank" rel="noopener">Fasting and diabetes</a></details><details><summary>Recent fasting history</summary><div id="fastHistory"></div></details></section>
<dialog id="bodyDialog"><form id="bodyForm"><div class="dialog-head"><h2>Your body profile</h2><button id="bodyClose" type="button" class="close" aria-label="Close profile">×</button></div><p class="metadata muted">Saved to your LasO account. Adult estimates only.</p><label>Units<select id="bodyUnits"><option value="us">Pounds & inches</option><option value="metric">Kilograms & centimeters</option></select></label><div class="two"><label>Age · years<input id="bodyAge" type="number" min="18" max="100" step="1" required></label><label>Sex coefficient<select id="bodySex" required><option value="">Choose</option><option value="female">Female</option><option value="male">Male</option></select></label><label><span id="heightLabel">Height · inches</span><input id="bodyHeight" type="number" min="1" step="0.1" required></label><label><span id="weightLabel">Weight · lb</span><input id="bodyWeight" type="number" min="1" step="0.1" required></label></div><p class="metadata muted">The original equation has two sex coefficients. If neither fits your situation, ask your clinician for a measured resting-energy value and set a goal manually.</p><label>Typical activity, including workouts<select id="bodyActivity"><option value="1.2">Mostly seated / little exercise</option><option value="1.375">Light activity</option><option value="1.55">Moderate activity</option><option value="1.725">High activity / active job</option></select></label><label>Goal<select id="bodyGoal"><option value="maintain">Maintain</option><option value="lose">Gradual loss</option><option value="gain">Gradual gain</option></select></label><label class="check"><input id="bodyCare" type="checkbox">Pregnancy, breastfeeding, an eating-disorder history, or a medical condition means I need an individualized plan.</label><label class="check"><input id="bodyShare" type="checkbox">Share my body stats and fasting history with Reginald for coaching. I can turn this off anytime.</label><p id="bodyError" class="error" role="alert"></p><button id="bodySave" class="primary full">Save my stats</button></form></dialog>`;
const message=t=>$('healthStatus').textContent=t;
const active=()=>fasts.find(f=>!f.ended_at);
function tick(){const f=active();$('fastClock').textContent=f?C.clock(C.elapsed(f.started_at)):'Not fasting';$('fastProgress').textContent=f?(f.target_hours?(C.elapsed(f.started_at)>=f.target_hours*3600000?'Personal time goal reached; no need to extend it':C.clock(f.target_hours*3600000-C.elapsed(f.started_at))+' until your '+f.target_hours+'h goal'):'Timer only · no duration prescribed'):'';}
function render(){const e=C.estimate(profile),box=$('bodyNumbers');box.replaceChildren();$('bodyEdit').textContent=profile?'Edit my stats':'Enter my stats';$('useEnergy').hidden=!e?.target;
if(e)for(const [label,val]of [['Resting energy · BMR estimate',e.rest],['Estimated maintenance',e.maintenance],['Suggested starting goal',e.target]]){const div=document.createElement('div'),n=document.createElement('strong'),s=document.createElement('span');n.textContent=val?val.toLocaleString()+' kcal':'Discuss with clinician';s.textContent=label;div.append(n,s);box.append(div);}
$('bodyNote').textContent=profile?.special_care?'Automatic recommendations are off. Use your individualized goal in Goals & sharing.':e?'Mifflin–St Jeor predicts resting energy; this is not a measured BMR. Maintenance uses your activity estimate. Loss/gain applies a 250 kcal adjustment. Review trends with your trainer. Workouts are already included—do not add those calories twice.':'No measurements or calorie goals are assumed.';
const f=active();$('fastSetup').hidden=!!f;$('fastStart').hidden=!!f;$('fastEnd').hidden=!f;tick();const list=$('fastHistory');list.replaceChildren();for(const r of fasts.filter(r=>r.ended_at)){const p=document.createElement('p');p.textContent=new Date(r.started_at).toLocaleDateString()+' · '+C.clock(new Date(r.ended_at)-new Date(r.started_at));list.append(p);}if(!list.children.length)list.textContent='No completed fasts.';}
async function refresh(force=false){const uid=getSession()?.user.id||null;if(!force&&uid===owner)return;if(uid!==owner){owner=uid;profile=null;fasts=[];if($('bodyDialog').open)$('bodyDialog').close();message('');render();}const n=++epoch;if(!uid)return;try{const [p,f]=await Promise.all([api('/rest/v1/nutrition_body_profiles?user_id=eq.'+uid+'&select=*'),api('/rest/v1/nutrition_fasts?user_id=eq.'+uid+'&select=*&order=started_at.desc&limit=20')]);if(n!==epoch||uid!==getSession()?.user.id)return;profile=p?.[0]||null;fasts=f||[];render();message('Synced with your LasO account.');}catch(e){if(n===epoch)message('Could not sync. '+e.message);}}
async function run(fn){if(pending)return;if(!getSession()){signIn();return;}pending=true;const uid=getSession().user.id;['bodySave','fastStart','fastEnd','useEnergy'].forEach(id=>$(id).disabled=true);try{await fn(uid);}catch(e){message(e.message);$('bodyError').textContent=e.message;}finally{pending=false;['bodySave','fastStart','fastEnd','useEnergy'].forEach(id=>$(id).disabled=false);if(uid!==getSession()?.user.id)await refresh(true);}}
function units(){const us=$('bodyUnits').value==='us';$('heightLabel').textContent='Height · '+(us?'inches':'cm');$('weightLabel').textContent='Weight · '+(us?'lb':'kg');}
$('bodyUnits').onchange=()=>{const us=$('bodyUnits').value==='us';for(const[id,k]of [['bodyHeight',2.54],['bodyWeight',0.45359237]])if($(id).value)$(id).value=(Number($(id).value)*(us?1/k:k)).toFixed(1);units();};
$('bodyEdit').onclick=()=>{if(!getSession()){signIn();return;}$('bodyForm').reset();$('bodyUnits').value=profile?.units||'us';const us=$('bodyUnits').value==='us';$('bodyAge').value=profile?.age_years||'';$('bodySex').value=profile?.equation_sex||'';$('bodyHeight').value=profile?(profile.height_cm/(us?2.54:1)).toFixed(1):'';$('bodyWeight').value=profile?(profile.weight_kg/(us?0.45359237:1)).toFixed(1):'';$('bodyActivity').value=profile?.activity_factor||1.2;$('bodyGoal').value=profile?.goal||'maintain';$('bodyCare').checked=profile?.special_care||false;$('bodyShare').checked=profile?.share_with_trainer||false;$('bodyError').textContent='';units();$('bodyDialog').showModal();};
$('bodyClose').onclick=()=>{if(!pending)$('bodyDialog').close();};
$('bodyForm').onsubmit=e=>{e.preventDefault();run(async uid=>{const us=$('bodyUnits').value==='us',p={user_id:uid,age_years:Number($('bodyAge').value),equation_sex:$('bodySex').value,height_cm:Number(($('bodyHeight').value*(us?2.54:1)).toFixed(2)),weight_kg:Number(($('bodyWeight').value*(us?0.45359237:1)).toFixed(2)),activity_factor:Number($('bodyActivity').value),goal:$('bodyGoal').value,special_care:$('bodyCare').checked,share_with_trainer:$('bodyShare').checked,coach_id:'a20479c8-1339-4443-bc7a-9a2346cd3e26',units:$('bodyUnits').value,updated_at:new Date().toISOString()};C.estimate({...p,special_care:false});const result=await api('/rest/v1/nutrition_body_profiles?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(p)});if(result?.length!==1)throw Error('Stats were not confirmed saved.');if(uid!==getSession()?.user.id)return;profile=result[0];render();$('bodyDialog').close();message(p.share_with_trainer?'Saved. Your trainer can access these stats and fasts.':'Saved privately to your account.');});};
$('useEnergy').onclick=()=>run(async uid=>{const target=C.estimate(profile)?.target;if(!target)return;const existing=await api('/rest/v1/nutrition_preferences?user_id=eq.'+uid+'&select=*'),p=existing?.[0]||{user_id:uid,display_name:getSession().user.user_metadata?.full_name||getSession().user.email||'My account',coach_id:'a20479c8-1339-4443-bc7a-9a2346cd3e26',share_with_coach:false};p.calorie_goal=target;p.updated_at=new Date().toISOString();const rows=await api('/rest/v1/nutrition_preferences?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(p)});if(rows?.length!==1)throw Error('Goal save not confirmed.');if(uid!==getSession()?.user.id)return;await onGoal();message('Your body gauge now uses '+target+' kcal.');});
$('fastStartTime').value=window.NutritionCore.localTime();
$('fastStart').onclick=()=>run(async uid=>{if(!$('fastEligible').checked)throw Error('Review the fasting suitability statement first.');if(profile?.special_care)throw Error('Your profile needs an individualized plan. Follow clinician guidance.');const start=new Date($('fastStartTime').value);if(!Number.isFinite(start.getTime())||start>Date.now()||Date.now()-start>7*86400000)throw Error('Choose a start within the past seven days.');const r=await api('/rest/v1/nutrition_fasts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:uid,started_at:start.toISOString(),target_hours:Number($('fastTarget').value)})});if(r?.length!==1)throw Error('Start was not confirmed saved.');await refresh(true);});
async function end(time){const f=active();if(!f)return;const when=new Date(time);if(!Number.isFinite(when.getTime())||when<new Date(f.started_at)||when>Date.now())throw Error('Check the fast end time.');const r=await api('/rest/v1/nutrition_fasts?id=eq.'+f.id+'&ended_at=is.null',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({ended_at:when.toISOString()})});await refresh(true);if(r?.length!==1)throw Error('This fast changed on another device. The tracker has refreshed.');}
$('fastEnd').onclick=()=>run(()=>end(new Date().toISOString()));$('fastRefresh').onclick=()=>refresh(true);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh(true);});setInterval(tick,15000);setInterval(()=>{if(document.visibilityState==='visible'&&owner&&!pending)refresh(true);},60000);
render();return {refresh,async mealSaved(time){const f=active();if(f&&new Date(time)>=new Date(f.started_at)&&new Date(time)<=Date.now()&&confirm('Meal saved. End your active fast at this meal time?'))await run(()=>end(time));}};
}};
})();
