(function(){'use strict';window.NutritionTraining={create({api,getSession,signIn,onDate}){
const $=id=>document.getElementById(id),make=(tag,text)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;return e;};
let uid=null,seq=0,data=null,offset=0,total=0,pending=false;
$('trainingPanel').innerHTML=`<section class="panel health-card"><div class="panel-head"><div><p class="eyebrow">ONE FITNESS HISTORY</p><h2>Your AI Trainer sessions</h2></div><button id="trainingRefresh">Refresh history</button></div><p class="metadata muted">Confirmed connections bring saved Trainer sessions, workouts, movement summaries and sensor sessions into your account. New records appear without copying them. Food and body sharing remain separate choices.</p><p id="trainingStatus" role="status"></p><div id="trainingLinks"></div><div id="trainingRecords"></div><div class="flex"><button id="trainingPrev" hidden>Newer</button><span id="trainingPage" class="metadata"></span><button id="trainingNext" hidden>Older</button></div></section>`;
$('coachHistory').innerHTML=`<h3>Connect Trainer history</h3><p class="metadata muted">Select the correct account and Trainer record. The client confirms before history appears. A profile connection includes its past and future sessions; individual trial sessions can be connected even without a profile.</p><label>App-E-Tight account<select id="linkAccount"></select></label><label>Trainer record<select id="linkSource"></select></label><button id="proposeHistory" class="primary">Request connection</button><p id="linkStatus" role="status"></p><div id="coachHistoryLinks"></div>`;
const rpc=(action,input={})=>api('/rest/v1/rpc/trainer_history_bridge',{method:'POST',body:JSON.stringify({p_action:action,p_input:input})});
function clear(){data=null;offset=0;total=0;for(const id of ['trainingLinks','trainingRecords','coachHistoryLinks','linkAccount','linkSource'])$(id).replaceChildren();$('trainingStatus').textContent='Sign in to see your connected training history.';$('trainingPage').textContent='';$('trainingPrev').hidden=true;$('trainingNext').hidden=true;}
async function act(action,input){if(pending)return;pending=true;try{await rpc(action,input);await refresh(true);$('linkStatus').textContent=action==='propose'?'Connection requested. The client confirms in their training-history panel.':'Connection updated.';}catch(e){$('linkStatus').textContent=e.code==='23505'?'This Trainer record already has a pending or accepted connection. Disconnect that link before reassigning it.':e.message;$('trainingStatus').textContent=e.message;}finally{pending=false;}}
function linkCard(l,coach=false){const box=make('div');box.className='coach-entry';const account=data.accounts.find(a=>a.user_id===l.user_id);box.append(make('strong',l.label),make('p',(coach?(account?.name||'Connected account')+' · ':'')+(l.client_id?'Trainer profile':'Individual session')+' · '+l.status));if(!coach&&l.status==='pending'){const b=make('button','Confirm this is my history');b.onclick=()=>{if(confirm('Confirm that “'+l.label+'” is your Trainer record. This will show its saved history in your account.'))act('accept',{link_id:l.id});};box.append(b);}const remove=make('button',l.status==='pending'?'Decline / cancel':'Disconnect');remove.onclick=()=>{if(confirm('Disconnect this history? The original Trainer records remain saved.'))act('revoke',{link_id:l.id});};box.append(remove);return box;}
function catalog(){const own=$('trainingLinks');own.replaceChildren();for(const l of data.links.filter(l=>l.user_id===uid))own.append(linkCard(l));const account=$('linkAccount'),source=$('linkSource'),old=account.value;account.replaceChildren(new Option('Choose client account',''));for(const a of data.accounts)account.append(new Option(a.name,a.user_id));if(data.accounts.some(a=>a.user_id===old))account.value=old;source.replaceChildren(new Option('Choose Trainer profile or trial session',''));for(const c of data.clients)source.append(new Option('PROFILE · '+c.label,'client:'+c.id));for(const s of data.sessions)source.append(new Option('SESSION · '+s.label+' · '+new Date(s.created_at).toLocaleDateString(),'invite:'+s.id));const target=$('coachHistoryLinks');target.replaceChildren();for(const l of data.links.filter(l=>l.coach_id===uid))target.append(linkCard(l,true));if(!data.accounts.length)$('linkStatus').textContent='Clients appear here after enabling journal sharing with you in Goals & sharing.';}
function human(k){return k.replaceAll('_',' ');}
function details(value,parent){for(const [key,v]of Object.entries(value||{})){if(v===null||v===undefined)continue;if(typeof v==='object'){const nested=make('details'),summary=make('summary',human(key));nested.append(summary);details(v,nested);parent.append(nested);}else{const p=make('p',human(key)+': '+String(v));p.className='metadata';parent.append(p);}}}
async function history(n){const user=uid;const h=await rpc('history',{offset});if(n!==seq||user!==getSession()?.user.id)return;total=h.total;const target=$('trainingRecords');target.replaceChildren();for(const r of h.records){const card=make('article');card.className='coach-entry';card.append(make('strong',r.title||human(r.kind)),make('p',new Date(r.occurred_at).toLocaleString()+' · '+human(r.kind)));const d=make('details');d.append(make('summary','View recorded details'));details(r.details,d);card.append(d);const meal=make('button','See nutrition that day');meal.onclick=()=>onDate(r.occurred_at);card.append(meal);target.append(card);}$('trainingStatus').textContent=total?'Synced from saved AI Trainer records. Capture gaps are not active exercise time.':'No history connected yet. Your trainer requests a connection; you confirm it here.';$('trainingPage').textContent=total?(offset+1)+'–'+Math.min(offset+50,total)+' of '+total:'';$('trainingPrev').hidden=offset===0;$('trainingNext').hidden=offset+50>=total;}
async function refresh(force=false){const current=getSession()?.user.id||null;if(!force&&uid===current)return;if(uid!==current){uid=current;clear();}const n=++seq;if(!uid)return;try{const c=await rpc('catalog');if(n!==seq||uid!==getSession()?.user.id)return;data=c;catalog();await history(n);}catch(e){if(n===seq)$('trainingStatus').textContent='Could not load training history. '+e.message;}}
$('trainingRefresh').onclick=()=>{if(!getSession()){signIn();return;}refresh(true);};$('trainingPrev').onclick=()=>{offset=Math.max(0,offset-50);refresh(true);};$('trainingNext').onclick=()=>{offset+=50;refresh(true);};
$('proposeHistory').onclick=()=>{const user_id=$('linkAccount').value,[kind,id]=$('linkSource').value.split(':');if(!user_id||!id){$('linkStatus').textContent='Choose both a client account and a Trainer record.';return;}const a=data.accounts.find(a=>a.user_id===user_id),s=$('linkSource').selectedOptions[0].textContent;if(confirm('Request connection for '+a.name+' to '+s+'? Check that both records belong to the same person.'))act('propose',{user_id,[kind==='client'?'client_id':'invite_id']:id});};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh(true);});setInterval(()=>{if(uid&&!pending&&document.visibilityState==='visible')refresh(true);},60000);clear();return {refresh};
}};})();
